name: VSCode Marketplace publish
on:
  push:
    tags:
      - "release-v[0-9]+.[0-9]+.[0-9]+"
jobs:
  publish:
    name: Publish to VSCode Marketplace
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install vsce
        run: npm install -g vsce
      - name: Install npm
        run: npm install
      - name: Publish to VSCode Marketplace
        run: npm run bundle && vsce publish -p ${{ secrets.AZURE_PAT }}